# Generated by Django 5.0.6 on 2024-06-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='preview',
            new_name='preview_image',
        ),
    ]
